theme: jekyll-theme-minimal
title: "Altronix Engine"
description: "Altronix Engine is a mod for Friday Night Funkin', including a full engine rework, replays, and more."
show_downloads: true
replace_index_with: "https://cors-thing.puyo.workers.dev/main/"
logo: "https://github.com/AltronMaxX/Altronix-Engine/raw/main/enginelogo.png"
url: "https://AltronMaxX.github.io/Altronix-Engine/"
