# This is a basic workflow to help you get started with Actions

name: Latest build release CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildWindows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    permissions:
       contents: write
       actions: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
          
      #Took caching functions from Codename Engine
      - name: Restore existing build cache for faster compilation
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
            export/debug/windows/haxe/
            export/debug/windows/obj/
            
      # Runs a set of commands using the runners shell
      - name: Setup everything and build release version
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
          haxelib run lime build windows
          haxelib run lime build windows --debug
        shell: cmd
        
      - name: Make release zip
        run: |
          7z a -tzip "engine.zip" "./export/release/windows/bin/*"
          
      - name: Build debug version
        run: |
          haxelib run lime build windows -debug
        shell: cmd
          
      - name: Make debug zip
        run: |
          7z a -tzip "engine-debug.zip" "./export/debug/windows/bin/*"
         
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: Latest build from action with id ${{github.run_number}}
          tag_name: Actions_Build_${{github.run_number}}
          files: |
            engine.zip
            engine-debug.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-windows") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
          
      - name: Save new cache
        uses: actions/cache/save@v3
        with:
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
            export/debug/windows/haxe/
            export/debug/windows/obj/
          key: cache-build-windows
